#include "token.h"

const char* const tok_names[] = {
    "BOOL",
    "NUMBER",
    "STRING",
    "IDENT",
    "PLUS",
    "MINUS",
    "SLASH",
    "ASTERISK",
    "ASSIGN",
    "PERCENT",
    "COLON",
    "FATARROW",
    "GREATERTHAN",
    "LESSTHAN",
    "EQUAL",
    "NOTEQUAL",
    "BANG",
    "GREATERTHANEQUAL",
    "LESSTHANEQUAL",
    "IF",
    "ELSEIF",
    "ELSE",
    "FUN",
    "END",
    "PASS",
    "ENDOFFILE",
    "NEWLINE",
    "ILLEGAL",
    "LPAREN",
    "RPAREN",
    "LBRACKET",
    "RBRACKET",
};
